exclude: &exclude_files >
    (?x)^(
        docs/.*|
        tests/.*|
        .github/.*|
        LICENSE.md|
        README.md|
    )$

ci:
  autoupdate_schedule: quarterly

default_stages: [pre-commit]

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        # MD013: line length
        # MD033: no inline HTML
        # MD041: first line in a file should be a top-level heading
        # MD034: bare URL used
        args: [--disable, MD013, MD033, MD041, MD034, '--']

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.2
    hooks:
    -   id: pylint
        language: system
        args: [
          '--disable=line-too-long',
          '--disable=no-member',
          '--disable=missing-module-docstring',
          '--disable=missing-class-docstring',
          '--disable=missing-function-docstring',
          '--disable=too-many-arguments',
          '--disable=too-many-positional-arguments',
          '--disable=too-many-locals',
          '--disable=not-callable',
          '--disable=logging-fstring-interpolation',
          '--disable=logging-not-lazy',
          '--disable=invalid-name',
          '--disable=too-few-public-methods',
          '--disable=too-many-instance-attributes',
          '--disable=too-many-statements',
          '--disable=too-many-branches',
          '--disable=import-outside-toplevel',
          '--disable=cell-var-from-loop',
          '--disable=duplicate-code',
          '--disable=use-dict-literal',
          '--max-module-lines=1500',
        ]
        exclude: *exclude_files
